version: '2'
services:
  web:
    build: .
    restart: always
    volumes:
      - ./static:/usr/src/app/static
      - ./img:/usr/src/app/img
    ports:
      - 5002:5002
  redis:
    image: redis
    volumes:
      - ./redis:/data
