version: '2'
services:
  web:
    build: .
    restart: always
    volumes:
      - ./static:/usr/src/app/static
      - ./img:/usr/src/app/img
    ports:
      - 5002:5002
  web-dev:
    build: .
    volumes:
     - .:/usr/src/app
    command: python manage.py runserver --host=0.0.0.0
    environment:
     - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
     - FLASK_CONFIG=development
    ports:
      - 5052:5052
