version: '2'
services:
  web:
    build: .
    restart: always
    volumes:
     - ./static:/usr/src/app/static
    ports:
      - 5000:5000
#  web-dev:
#    build: .
#    volumes:
#     - .:/usr/src/app
#    command: python manage.py runserver --host=0.0.0.0 --port=5050
#    environment:
#     - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
#     - FLASK_CONFIG=development
#    ports:
#      - 5050:5050
#    restart: always
  redis:
    image: redis
    volumes:
      - ./redis:/data

